### ISSUE TITLE
Bridge.NET (non-WASM) support?

### ISSUE THREAD

**Issue by zezba9000** [nventive/Uno#115]
Bridge.NET loads and runs much faster than Mono-WASM right now. It also runs on more browsers.

Any idea how hard would this be?

ALSO: How does Uno render elements? Using the native vector rendering engine on each platform? Canvas(HTML), Cocoa(iOS), etc?

**Comment by jeromelaban** [comment]
We investigated a while back Bridge.NET and unfortunately, while being a brilliant piece of technology, it does not fit the needs of Uno Platform's code sharing with iOS and Android. The behaviors of .NET BCL and runtime, particularly around memory management and reflection, are significantly different or completely absent, we would have to specifically adapt very large portions of tricky parts of the architecture.

While mono-wasm is slower at the moment, its runtime and BCL behavior is exactly the same as on the other platforms (iOS, Android, linux, etc...) and to a very large extent -- due to the BCL code sharing -- to .NET Core and desktop. This makes for a more viable target on the mid-term as we don't have to battle the underlying framework to make progress in Uno (as well as other libraries like Rx, RxUI, Prism, MVVMLight, etc...).

As for the rendering, Uno is using the native view hierarchy for the rendering (UIView, ViewGroup and Html divs) with drawing primitives associated to them (CGLayer, Drawables, CSS on Divs). The use of native presenters (UIButton, Button, HTML Input) is up to the choice of the developer ([XAML-Based](https://github.com/nventive/Uno/blob/f04b83bdb12e1c8d24fcd7633ce7b0996749a869/src/Uno.UI/UI/Xaml/Style/Generic/Generic.xaml#L205) or [native based](https://github.com/nventive/Uno/blob/f04b83bdb12e1c8d24fcd7633ce7b0996749a869/src/Uno.UI/UI/Xaml/Style/Generic/Generic.Native.xaml#L36)). There are only a few controls that are always native like the `TextBox`, because it's heavily tied to platform features such as dictation, spell checking, automation and very important accessibility features.

**Comment by zezba9000** [comment]
Tnx for info
