### ISSUE TITLE
Reflection & WASM, assembly got linked.

### ISSUE THREAD

**Issue by CobraCalle** [nventive/Uno#145]
I have a class like this…

    [Operation("+", 20)]
    public class Add : Operation
    {
        internal Add(Formula formula, Value left, Value right)
            : base(formula, left, right)
        {
        }
}

Now I what to create this type by reflection and try to get the constructor…

                    System.Reflection.ConstructorInfo constructor = operation.GetConstructor(System.Reflection.BindingFlags.Instance | System.Reflection.BindingFlags.NonPublic, null, new Type[] { typeof(Diomex.Framework.Math.FormulaParser.Formula), typeof(Diomex.Framework.Math.FormulaParser.Value), typeof(Diomex.Framework.Math.FormulaParser.Value) }, null);

"operation" is here typeof(Add)

This works well… except in the WASM-version… there is constructor null

Any ideas?

**Comment by carldebilly** [comment]
That's because your assembly got _linked_ during compilation. This means the linker considers this constructor is never called and get rid of it.

You can hint the linker like we did in the playground:
1. Create a file called `LinkerConfig.xml` like this: <https://github.com/nventive/Uno.Playground/blob/master/src/Uno.Playground.WASM/LinkerConfig.xml> and add relevant assemblies/namespaces/types. You can find the documentation here: <https://github.com/mono/linker/tree/master/linker#syntax-of-xml-descriptor>
2. Reference your file in the `.csproj` link this: <https://github.com/nventive/Uno.Playground/blob/master/src/Uno.Playground.WASM/Uno.Playground.WASM.csproj#L43>

**Comment by carldebilly** [comment]
Please close the issue of you're satisfied with the answer.
