### ISSUE TITLE
Please implement UIElement Pointer Event and AddHandler/RemoveHandler methods

### ISSUE THREAD

**Issue by Daoting** [nventive/Uno#146]
It's important for custom controls. App can't run when migrate existing controls.

**Comment by yowl** [comment]
Is this related to https://github.com/nventive/Uno/pull/160 ?

**Comment by carldebilly** [comment]
Which events are you interested in?

**Comment by Daoting** [comment]
Yes, [#160](https://github.com/nventive/Uno/pull/160), thanks @carldebilly

**Comment by carldebilly** [comment]
The PR won't be merged this week because of coordination with other projects. But if you want, you can pre-test your code with the nuget package from the CI server. Here's how to get it:

1. Go to PR #160 
2. Click `Show all checks` and `details` (in the summary at the bottom of the page)
3. On _Azure DevOps_, click on the _Summary_ view
4. Download the `NugetPackages` (it's a zip file)
5. You'll find the nuget package in the `vslatest` folder

If you find any problem, please report it here on this issue.

**Comment by yowl** [comment]
I'd like to have a go at this, https://github.com/nventive/Uno/issues/146#issuecomment-439950852, but in the nuget zip there is the vsix, but no .nupkg.  Is that right , or are the warnings/errors causing the nupkg artifact to not be generated?

**Comment by carldebilly** [comment]
I think it's because the build didn't went well and is not completed for this commit.

**Comment by carldebilly** [comment]
It's merged now.
