### ISSUE TITLE
ComboBox incorrect behavior when using Items property

### ISSUE THREAD

**Issue by jeromelaban** [nventive/Uno#87]
Using this simple sample, the list is modified at each selection:

```xml
<ComboBox>
	<ComboBoxItem>Value 1</ComboBoxItem>
	<ComboBoxItem>Value 2</ComboBoxItem>
	<ComboBoxItem>Value 3</ComboBoxItem>
</ComboBox>
```

Observed with `Uno.UI 1.31.0-dev.94`.

**Comment by double28** [comment]
in android,the last selected item dispeared! in ios,no item show!

**Comment by leboeuf** [comment]
Here the items are of type ComboBoxItem, which is a view.
Since views can only have one parent, when `ComboBox.UpdateContentPresenter()` sets its `_contentPresenter.Content` to the SelectedItem, the parent of the item becomes that ContentPresenter, which explains why it's not in the dropdown list anymore.

One option would be to implement in Uno the specifics of CarouselPanel that make the dropdown expand around the selected item (if we want the same behavior as UWP).
If you simply want to display strings in your ComboBox I suggest that you use the ItemsSource attribute instead of creating ComboBoxItems manually.

**Comment by double28** [comment]
In android,i can define a ItemTemplate of ComboBox,then the behaviour of ComboBox is well.
In IOS, it's not work still! I define a List<string> as the ItemsSource value,it's still show nothing.

@jeromelaban ,do you know How to deal with it? Thank you!

**Comment by XiaotianNetlift** [comment]
If you need to set the choices in xaml, you can use the [primitives literals](https://docs.microsoft.com/en-us/dotnet/framework/xaml-services/built-in-types-for-common-xaml-language-primitives) as a temporary workaround:

    <ComboBox>
        <x:String>Red</x:String>
        <x:String>Green</x:String>
        <x:String>Blue</x:String>
    </ComboBox>

Using a list for `ItemsSource` should work on both on ios & android. And, depending on what type of the list you get, you might need to set the `DisplayMemberPath`.
